// JavaScript Document
var idaddress="",togglebox="";function loaddevices(a,c,f){if(1==c)var g="make";else 2==c?g="devices":3==c&&(g="model");$("#"+g+"> div").click(function(a){a.preventDefault();$("#"+g+"> div > div > div > div").removeClass("success");$(this+"> div > div > div").addClass("success")});var l=jQuery("#storeurl").val();idaddress=f;togglebox=g+"_1";jQuery.ajax({type:"POST",url:l+"/includes/content/loadrepairs.php",data:"catid="+a+"&level="+c,success:success,error:connectionerror})}
function loaddetails(a,c,f){$("#problems > div").click(function(a){a.preventDefault();$("#problems > div > div").removeClass("success");$(this+"> div > div > div").addClass("success")});var g=jQuery("#storeurl").val();idaddress=f;jQuery.ajax({type:"POST",url:g+"/includes/content/loaddetails.php",data:"proid="+a+"&level="+c,success:successdetails,error:connectionerror})}function connectionerror(a,c,f){alert("System is unable to connect to server")}
function successdetails(a){a=a.split("::");1==a[0]&&($("#"+idaddress).addClass("success"),$("#problemdetail").css("display","block"),document.getElementById("problemtit").innerHTML=a[1],document.getElementById("problemprice").innerHTML=a[2],document.getElementById("probtree").innerHTML=a[5],document.getElementById("contactus").href=a[6],document.getElementById("repairid").href=a[7],$("#problems_1").slideUp(1E3))}
function success(a){a=a.split("::");1==a[0]?(1==a[1]?(document.getElementById("devices").innerHTML=a[2],$("#devices").css("display","block"),$("#"+idaddress).addClass("success"),document.getElementById("model").innerHTML="",document.getElementById("problems").innerHTML="",$("#model").css("display","none"),$("#problems").css("display","none"),$("#problemdetail").css("display","none")):2==a[1]?(document.getElementById("model").innerHTML=a[2],$("#model").css("display","block"),$("#"+idaddress).addClass("success"),
document.getElementById("problems").innerHTML="",$("#problems").css("display","none"),$("#problemdetail").css("display","none")):3==a[1]&&(7==a[3]&&(document.getElementById("model").innerHTML="",$("#model").css("display","none")),document.getElementById("problems").innerHTML=a[2],$("#problems").css("display","block"),$("#"+idaddress).addClass("success"),$("#problemdetail").css("display","none")),$("#"+togglebox).slideUp(1E3)):2==a[0]&&(1==a[1]?(document.getElementById("devices").innerHTML="",document.getElementById("model").innerHTML=
"",document.getElementById("problems").innerHTML="",$("#devices").css("display","none"),$("#model").css("display","none"),$("#problems").css("display","none"),$("#problemdetail").css("display","none")):2==a[1]?(document.getElementById("model").innerHTML="",document.getElementById("problems").innerHTML="",$("#model").css("display","none"),$("#problems").css("display","none"),$("#problemdetail").css("display","none")):3==a[1]&&(document.getElementById("problems").innerHTML="",$("#problems").css("display",
"none"),$("#problemdetail").css("display","none")))}
function loaddevicess(a,c,f){if(1==f){var g=$j("#make option:selected").text();document.getElementById("make_d").value=g}else 2==f?(g=$j("#device option:selected").text(),document.getElementById("device_d").value=g):3==f&&(g=$j("#model option:selected").text(),document.getElementById("model_d").value=g);jQuery.ajax({type:"POST",url:a+"/admin/sources/repair/loadrepairs.php",data:"catid="+c+"&level="+f,success:successadmin,error:connectionerror})}
function successadmin(a){a=a.split("::");1==a[2]?1==a[1]?(document.getElementById("device").innerHTML=a[0],document.getElementById("model").innerHTML="",document.getElementById("problem").innerHTML=""):2==a[1]?(document.getElementById("model").innerHTML=a[0],document.getElementById("problem").innerHTML=""):3==a[1]&&(document.getElementById("problem").innerHTML=a[0]):2==a[0]&&(1==a[1]?(document.getElementById("device").innerHTML="",document.getElementById("model").innerHTML="",document.getElementById("problem").innerHTML=
""):2==a[1]?(document.getElementById("model").innerHTML="",document.getElementById("problem").innerHTML=""):3==a[1]&&(document.getElementById("problem").innerHTML="",$("#problem").css("display","none")))}function loaddetailss(a,c,f){var g=$j("#probleme option:selected").text();document.getElementById("problem_d").value=g;jQuery.ajax({type:"POST",url:a+"/admin/sources/repair/loaddetails.php",data:"proid="+c+"&level="+f,success:successdetailss,error:connectionerror})}
function successdetailss(a){a=a.split("::");1==a[0]&&(document.getElementById("prob_price").value=a[1])}function togglethis(a){$("#"+a).is(":visible")?$("#"+a).slideUp(1E3):$("#"+a).slideDown(1E3)};function loginAuth(){var a=jQuery("#storeurl").val();document.getElementById("loginAuthenticate").style.display="none";document.getElementById("loader").style.display="inline-block";jQuery.ajax({type:"POST",url:a+"/includes/content/ajaxAuthenticate.inc.php",data:"username="+jQuery("#login_email").val()+"&password="+jQuery("#login_password").val(),success:LoginSuccess,error:LoginError})}function LoginError(a,c,f){alert("System is unable to connect to server")}
function LoginSuccess(a){if(1==a){a=jQuery("#login_email").val();var c=jQuery("#login_password").val(),f=!0==jQuery("#login_remember").attr("checked")?1:0,g=1==document.getElementById("logredir").value?1:0;jQuery("#email").val(a);jQuery("#password").val(c);jQuery("#remember").val(f);jQuery("#redir").val(g);jQuery("#frmLoginBox").submit()}else jQuery("#loginFailedBox_error").fadeIn("slow").animate({opacity:1},3E3).fadeOut("slow"),document.getElementById("loginAuthenticate").style.display="inline-block",
document.getElementById("loader").style.display="none"}
function ValidateRegister(){if(""==document.getElementById("fname").value||""!=document.getElementById("fname").value&&!0==Validate(document.getElementById("fname").value,"[^A-Za-z+\\-\\ ]"))return $("#fname").css("background-color","#FFCECE"),document.getElementById("fname").focus(),!1;if(""==document.getElementById("txtEmail").value)return $("#txtEmail").css("background-color","#FFCECE"),document.getElementById("txtEmail").focus(),!1;if(""!=document.getElementById("txtEmail").value&&!1==Validate(document.getElementById("txtEmail").value,
"[A-Za-z0-9_\\.][A-Za-z]*@[-A-Za-z]*\\.[A-Za-z0-9]"))return $("#txtEmail").css("background-color","#FFCECE"),document.getElementById("mbrEmailExist").innerHTML="",document.getElementById("txtEmail").focus(),!1;if(""==document.getElementById("txtphone").value)return $("#txtphone").css("background-color","#FFCECE"),document.getElementById("txtphone").focus(),!1;if(""==document.getElementById("txtpwd").value)return $("#txtpwd").css("background-color","#FFCECE"),document.getElementById("txtpwd").focus(),
!1;if(""==document.getElementById("cpassword").value)return $("#cpassword").css("background-color","#FFCECE"),document.getElementById("cpassword").focus(),!1;if(document.getElementById("cpassword").value!=document.getElementById("txtpwd").value)return document.getElementById("err_cpassword").innerHTML="Not Matched",document.getElementById("cpassword").focus(),!1;document.getElementById("err_cpassword").innerHTML="";if(!1==document.getElementById("tacon").checked)return document.getElementById("err_fname").innerHTML=
"Read Term and Conditions",document.getElementById("tacon").focus(),!1;document.getElementById("tacond").innerHTML="";return 1==document.getElementById("email_exist_flag").value?!0:!1}function Validatequantity(){var a=document.getElementById("quan").value,c=document.getElementById("mquan").value;if(a<parseInt(c))return document.getElementById("qerror").innerHTML="Minnimum Quantity for this product is "+c,!1}function Validate(a,c){return!0==RegExp(c,"g").test(a)?!0:!1}
function EmailExist(){var a=jQuery("#storeurl").val();mbrEmail=document.getElementById("txtEmail").value;if(""!=mbrEmail){if(!1==Validate(document.getElementById("txtEmail").value,"[A-Za-z0-9_\\.][A-Za-z]*@[-A-Za-z0-9]*\\.[A-Za-z0-9]"))return document.getElementById("err_email").innerHTML="Invalid Email",document.getElementById("mbrEmailExist").innerHTML="",!1;jQuery("#mbrEmailExist").load(a+"/js/check-email-existance.php?email="+mbrEmail);document.getElementById("err_email").innerHTML=""}}
function RemoveProduct(a,c){var f=jQuery("#storeurl").val();jQuery.ajax({type:"POST",url:f+"/includes/content/ajaxBasket.inc.php",data:"remove="+a+"&prdid="+c+"&basketcount="+jQuery("#basketcount").val(),success:BasketSuccess,error:BasketError})}
function BasketPage(){var a=jQuery("#storeurl").val();""!=jQuery("#txtcoupon").val()?jQuery.ajax({type:"POST",url:a+"/includes/content/ajaxBasket.inc.php",data:"coupon="+jQuery("#txtcoupon").val(),success:BasketPageSuccess,error:BasketError}):document.getElementById("errorDiscount").style.display=""}
function BasketPageSuccess(a){a=a.split("::");1==a[0]?(document.getElementById("IdCouponCodeDiv").innerHTML=a[1],document.getElementById("IdCartTotal").innerHTML=a[2],document.getElementById("paypalfee").innerHTML=a[3]):jQuery("#cart").submit()}function RemoveCouponCode(a){var c=jQuery("#storeurl").val();jQuery.ajax({type:"POST",url:c+"/includes/content/ajaxBasket.inc.php",data:"remCode="+a+"&basketcount="+jQuery("#basketcount").val(),success:BasketPageSuccess,error:BasketError})}
function BasketSuccess(a){a=a.split("::");1==a[0]?(document.getElementById("IdBasketData").innerHTML=a[1],document.getElementById("IdCartItem").innerHTML=a[3],document.getElementById("IdCartTotal").innerHTML=a[2],document.getElementById("paypalfee").innerHTML=a[5]):jQuery("#cart").submit()}function Checkout(){var a=jQuery("#storeurl").val();jQuery.ajax({type:"POST",url:a+"/includes/content/ajaxBasket.inc.php",data:"checkoutval=1",success:CheckoutSuccess,error:BasketError})}
function CheckoutSuccess(a){var c=jQuery("#storeurl").val();0==a?window.location=c+"/index.php?_g=co&_a=step3":jQuery("a.basketbox").click()}function BasketError(){alert("error ouccured during loading page.")}function ShowBasket(){jQuery("#basketbox").click()}function loginredir(){document.getElementById("logredir").value=1;jQuery("#cart-box a.close").click()}function isNumberKey(a){a=a.which?a.which:event.keyCode;return 31<a&&(48>a||57<a)?!1:!0}
function changebg(){$("#tco").hasClass("checkboxcheck")?($("#tacond").attr("checked",!1),$("#tco").removeClass("checkboxcheck")):($("#tacond").attr("checked",!0),$("#tco").addClass("checkboxcheck"))}function changebg2(){$("#billing").slideToggle();$("#tco2").hasClass("checkboxcheck")?($("#tacond2").attr("checked",!1),$("#tco2").removeClass("checkboxcheck")):($("#tacond2").attr("checked",!0),$("#tco2").addClass("checkboxcheck"))}
function changebg1(){$("#billing").slideToggle();$("#tco1").hasClass("checkboxcheck")?($("#sameaddress").attr("checked",!1),$("#tco1").removeClass("checkboxcheck")):($("#sameaddress").attr("checked",!0),$("#tco1").addClass("checkboxcheck"))}function Validateproduct(){if($("#txtimei").hasClass("error")||15>$("#txtimei").val().length)return!1;if(15>$("#txtimeii").val().length)return $("#txtimeii").focus(),$("#txtimeii").css("background-color","#FFCECE"),!1}
function changeopt(a,c){$("#selcetproductdetail").val(a);$("#selectedopt").text(c)}if("undefined"===typeof imei_length)var imei_length=15;if("undefined"===typeof use_letters)var use_letters=!1;if("undefined"===typeof use_minus)var use_minus=!1;if("undefined"===typeof use_alert)var use_alert=!1;function alltrim(a){return a.replace(/^\s+|\s+$/g,"")}
function keyup_imei(){imeisText=$("#txtimei").val();imeisText=imeisText.replace(/([\n|\r|\s])/g,"_");imeisText=imeisText.replace(/[_]+$/g,"");imeis=unescape(imeisText).split("_");unlocks_count=0;imeisLen=imeis.length;errors=!1;if(0<imeisLen)for(i=0;i<imeisLen;i++)0<imeis[i].length&&(str=alltrim(imeis[i]),str.length!=imei_length?errors=!0:(testul=use_minus?/^[a-z0-9-]{4}-[a-z0-9-]{4}/i.test(str):use_letters?/^[a-z0-9]/i.test(str):/^[-+]?[0-9]+$/.test(str))?unlocks_count++:errors=!0);errors?$("#txtimei").addClass("error"):
$("#txtimei").removeClass("error");var a=$("#cost_1_unlock").val(),c=$("#symbolleft").val();$("#totalprice").html(c+parseFloat(unlocks_count*a).toFixed(2))}function updateshipkey(a){var c=jQuery("#storeurl").val();jQuery.ajax({type:"POST",url:c+"/includes/content/ajaxBasket.inc.php",data:"shipKey="+a,success:updateshipprice,error:BasketError})}function updateshipprice(a){a=a.split("::");document.getElementById("IdCartTotal").innerHTML=a[1]};(function(a){var c={preloadImg:!0},f=function(b){var e=a(b.get(0).form),d=b.next();d.is("label")||(d=b.prev(),d.is("label")&&(b=b.attr("id"))&&(d=e.find('label[for="'+b+'"]')));return d.is("label")?d.css("cursor","pointer"):!1},g=function(b){a(".jqTransformSelectWrapper ul:visible").each(function(){var e=a(this).parents(".jqTransformSelectWrapper:first").find("select").get(0);b&&e.oLabel&&e.oLabel.get(0)==b.get(0)||a(this).hide()})},l=function(b){0===a(b.target).parents(".jqTransformSelectWrapper").length&&
g(a(b.target))},m=function(b){var e;a(".jqTransformSelectWrapper select",b).each(function(){e=0>this.selectedIndex?0:this.selectedIndex;a("ul",a(this).parent()).each(function(){a("a:eq("+e+")",this).click()})});a("a.jqTransformCheckbox, a.jqTransformRadio",b).removeClass("jqTransformChecked");a("input:checkbox, input:radio",b).each(function(){this.checked&&a("a",a(this).parent()).addClass("jqTransformChecked")})};a.fn.jqTransInputButton=function(){return this.each(function(){var b=a('<button id="'+
this.id+'" name="'+this.name+'" type="'+this.type+'" class="'+this.className+' jqTransformButton"><span><span>'+a(this).attr("value")+"</span></span>").hover(function(){b.addClass("jqTransformButton_hover")},function(){b.removeClass("jqTransformButton_hover")}).mousedown(function(){b.addClass("jqTransformButton_click")}).mouseup(function(){b.removeClass("jqTransformButton_click")});a(this).replaceWith(b)})};a.fn.jqTransInputText=function(){return this.each(function(){var b=a(this);if(!b.hasClass("jqtranformdone")&&
b.is("input")){b.addClass("jqtranformdone");var e=f(a(this));e&&e.bind("click",function(){b.focus()});e=b.width();b.attr("size")&&(e=10*b.attr("size"),b.css("width",e));b.addClass("jqTransformInput").wrap('<div class="jqTransformInputWrapper"><div class="jqTransformInputInner"><div></div></div></div>');var d=b.parent().parent().parent();d.css("width",e+10);b.focus(function(){d.addClass("jqTransformInputWrapper_focus")}).blur(function(){d.removeClass("jqTransformInputWrapper_focus")}).hover(function(){d.addClass("jqTransformInputWrapper_hover")},
function(){d.removeClass("jqTransformInputWrapper_hover")});a.browser.safari&&d.addClass("jqTransformSafari");a.browser.safari&&b.css("width",d.width()+16);this.wrapper=d}})};a.fn.jqTransCheckBox=function(){return this.each(function(){if(!a(this).hasClass("jqTransformHidden")){var b=a(this),e=f(b);e&&e.click(function(){d.trigger("click")});var d=a('<a href="#" class="jqTransformCheckbox"></a>');b.addClass("jqTransformHidden").wrap('<span class="jqTransformCheckboxWrapper"></span>').parent().prepend(d);
b.change(function(){this.checked&&d.addClass("jqTransformChecked")||d.removeClass("jqTransformChecked");return!0});d.click(function(){if(b.attr("disabled"))return!1;b.trigger("click").trigger("change");return!1});this.checked&&d.addClass("jqTransformChecked")}})};a.fn.jqTransRadio=function(){return this.each(function(){if(!a(this).hasClass("jqTransformHidden")){var b=a(this),e=this;(oLabel=f(b))&&oLabel.click(function(){d.trigger("click")});var d=a('<a href="#" class="jqTransformRadio" rel="'+this.name+
'"></a>');b.addClass("jqTransformHidden").wrap('<span class="jqTransformRadioWrapper"></span>').parent().prepend(d);b.change(function(){e.checked&&d.addClass("jqTransformChecked")||d.removeClass("jqTransformChecked");return!0});d.click(function(){if(b.attr("disabled"))return!1;b.trigger("click").trigger("change");a('input[name="'+b.attr("name")+'"]',e.form).not(b).each(function(){"radio"==a(this).attr("type")&&a(this).trigger("change")});return!1});e.checked&&d.addClass("jqTransformChecked")}})};
a.fn.jqTransTextarea=function(){return this.each(function(){var b=a(this);if(!b.hasClass("jqtransformdone")){b.addClass("jqtransformdone");(oLabel=f(b))&&oLabel.click(function(){b.focus()});var e;e='<table cellspacing="0" cellpadding="0" border="0" class="jqTransformTextarea"><tr><td id="jqTransformTextarea-tl"></td><td id="jqTransformTextarea-tm"></td><td id="jqTransformTextarea-tr"></td></tr><tr><td id="jqTransformTextarea-ml">&nbsp;</td><td id="jqTransformTextarea-mm"><div></div></td><td id="jqTransformTextarea-mr">&nbsp;</td></tr>';
e+='<tr><td id="jqTransformTextarea-bl"></td><td id="jqTransformTextarea-bm"></td><td id="jqTransformTextarea-br"></td></tr>';e+="</table>";var d=a(e).insertAfter(b).hover(function(){!d.hasClass("jqTransformTextarea-focus")&&d.addClass("jqTransformTextarea-hover")},function(){d.removeClass("jqTransformTextarea-hover")});b.focus(function(){d.removeClass("jqTransformTextarea-hover").addClass("jqTransformTextarea-focus")}).blur(function(){d.removeClass("jqTransformTextarea-focus")}).appendTo(a("#jqTransformTextarea-mm div",
d));this.oTable=d;a.browser.safari&&a("#jqTransformTextarea-mm",d).addClass("jqTransformSafariTextarea").find("div").css("height",b.height()).css("width",b.width())}})};a.fn.jqTransSelect=function(){return this.each(function(b){var e=a(this);if(!e.hasClass("jqTransformHidden")&&!e.attr("multiple")){var d=f(e),c=e.addClass("jqTransformHidden").wrap('<div class="jqTransformSelectWrapper"></div>').parent().css({zIndex:10-b});c.prepend('<div><span></span><a href="#" class="jqTransformSelectOpen"></a></div><ul></ul>');
var h=a("ul",c).css("width",e.width()).hide();a("option",this).each(function(b){b=a('<li><a href="#" index="'+b+'">'+a(this).html()+"</a></li>");h.append(b)});h.find("a").click(function(){a("a.selected",c).removeClass("selected");a(this).addClass("selected");e[0].selectedIndex!=a(this).attr("index")&&e[0].onchange&&(e[0].selectedIndex=a(this).attr("index"),e[0].onchange());e[0].selectedIndex=a(this).attr("index");a("span:eq(0)",c).html(a(this).html());h.hide();return!1});a("a:eq("+this.selectedIndex+
")",h).click();a("span:first",c).click(function(){a("a.jqTransformSelectOpen",c).trigger("click")});d&&d.click(function(){a("a.jqTransformSelectOpen",c).trigger("click")});this.oLabel=d;var k=a("a.jqTransformSelectOpen",c).click(function(){"none"==h.css("display")&&g();if(e.attr("disabled"))return!1;h.slideToggle("fast",function(){var b=a("a.selected",h).offset().top-h.offset().top;h.animate({scrollTop:b})});return!1});b=e.outerWidth();d=a("span:first",c);k=b>d.innerWidth()?b+k.outerWidth():c.width();
c.css("width",k);h.css("width",k-2);d.css({width:b});h.css({display:"block",visibility:"hidden"});b=a("li",h).length*a("li:first",h).height();b<h.height()&&h.css({height:b,overflow:"hidden"});h.css({display:"none",visibility:"visible"})}})};a.fn.jqTransform=function(b){a.extend({},c,b);return this.each(function(){var b=a(this);b.hasClass("jqtransformdone")||(b.addClass("jqtransformdone"),a('input:submit, input:reset, input[type="button"]',this).jqTransInputButton(),a("input:text, input:password",
this).jqTransInputText(),a("input:checkbox",this).jqTransCheckBox(),a("input:radio",this).jqTransRadio(),a("textarea",this).jqTransTextarea(),0<a("select",this).jqTransSelect().length&&a(document).mousedown(l),b.bind("reset",function(){window.setTimeout(function(){m(this)},10)}))})}})(jQuery);
function optIn1st(){$("#optIn1s").hasClass("checkboxcheck")?($("#optIn1st").attr("checked",!1),$("#optIn1s").removeClass("checkboxcheck")):($("#optIn1st").attr("checked",!0),$("#optIn1s").addClass("checkboxcheck"))}